# Generated by Django 3.1.6 on 2021-02-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Car make')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Car model')),
            ],
            options={
                'ordering': ['make'],
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rate')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_set', to='api.car')),
            ],
        ),
    ]
