# Generated by Django 3.1.6 on 2021-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210203_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Popular',
            new_name='Rate',
        ),
    ]
