# Generated by Django 3.1.6 on 2021-02-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210203_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_set', to='api.car'),
        ),
    ]
